version: "3"

services:
  mysql57-3306:
    image: mysql:5.7
    container_name: mysql:57-3306
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./cnf/mysql-57-3306.cnf:/root/.my.cnf:ro
