version: "3"

services:
  mysql57-3306:
    image: mysql:5.7
    container_name: mysql-57-3306
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./mysql-57-3306.cnf:/etc/mysql/conf.d/mysql-57-3306.cnf
  mysql57-3307:
    image: mysql:5.7
    container_name: mysql-57-3307
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./mysql-57-3307.cnf:/etc/mysql/conf.d/mysql-57-3306.cnf
